wx:
  datasource:
    masterSlave: true
spring:
#排除原生Druid的快速配置类
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: koala
    dynamic:
      druid: #以下是支持的全局默认值
        #连接池配置
        initial-size: 10
        max-active: 100
        max-evictable-idle-time-millis: 60000
        max-pool-prepared-statement-per-connection-size: 20
        max-wait: 10000
        min-evictable-idle-time-millis: 30000
        min-idle: 5
        pool-prepared-statements: true
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout: 5000
#        connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
        #配置多个英文逗号分隔
        filters: stat,wall,slf4j
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 5000
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          #JDBC 配置
          url: jdbc:mysql://localhost:3306/vaccine?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
          username: root
          password: ENC(hucVa+HZKkEVJUd8pQ63XBpbFG3sMLN67EKi3gypUf87MiCDW4jV4txt+jMzQtsf3+BLn75yOAoAutqvpA+sMg==)
          driver-class-name: com.mysql.cj.jdbc.Driver
          public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI9gPmj8aR6VhewVAbAEAv4mmTzDA6iUbWbWeH1LBV+PM++uCjF2BNM+GO4tWTmkakoBtlxTiafGZmoI3t5uFhMCAwEAAQ==
        slave_1:
          #JDBC 配置
          url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
          username: root
          password: ENC(VZamSTMi224AH6RUtJGXNldiDp/XEL2ozRhBUu/o9ChodT4JEb9kE/j0EFhXKbjsfvLVacUW0AUzetA6OrNJug==)
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          #JDBC 配置
          url: jdbc:mysql://localhost:3306/iccst?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
          username: root
          password: ENC(VZamSTMi224AH6RUtJGXNldiDp/XEL2ozRhBUu/o9ChodT4JEb9kE/j0EFhXKbjsfvLVacUW0AUzetA6OrNJug==)
          driver-class-name: com.mysql.cj.jdbc.Driver
      strategy: com.baomidou.dynamic.datasource.strategy.RandomDynamicDataSourceStrategy
      seata: true
pagehelper:
  #指定数据库，不指定的话会默认自动检测数据库类型
  helperDialect: mysql
  # 是否启用分页合理化。
  # 如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；
  # 不启用的，以上两种情况都会返回空数据
  reasonable: true
mybatis-plus:
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
#seata配置
seata:
  enabled: true
  config:
    type: nacos
    nacos:
      server-addr: 10.200.1.27:8848
      group: "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
  enable-auto-data-source-proxy: false
  application-id: wx-ceshi
  tx-service-group: wx-ceshi-seata-service-group # 事务群  组（可以每个应用独立取名，也可以使用相同的名字）
  client:
    rm:
      report-success-enable: true
      table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
      report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
      async-commit-buffer-limit: 10000 # 异步提交缓存队列长度（默认10000）
      lock:
        retry-interval: 10 # 校验或占用全局锁重试间隔（默认10ms）
        retry-times:    30 # 校验或占用全局锁重试次数（默认30）
        retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
    tm:
      commit-retry-count:   3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
      rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    undo:
      data-validation: true # 二阶段回滚镜像校验（默认true开启）
      log-serialization: jackson # undo序列化方式（默认jackson）
      log-table: undo_log  # 自定义undo表名（默认undo_log）
    log:
      exceptionRate: 100 # 日志异常输出概率（默认100）
  service:
    vgroup-mapping:
      wx-ceshi-seata-service-group: default # TC 集群（必须与seata-server保持一致）
    enable-degrade: false # 降级开关
    disable-global-transaction: false # 禁用全局事务（默认false）
    grouplist:
      default: 10.200.1.32:8091
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）

