wx:
  cache:
    type: MULTI
    caffeine-config: initialCapacity=10,maximumSize=500,expireAfterWrite=1800s
    redis-enable-transaction: false
    redisTtl: 1800
spring:
  redis:
    database: 10
    timeout: PT10S
#单机配置
    host: 10.200.1.32
    port: 6379
# 配置使用Lettuce连接池
    lettuce:
      pool:
        max-active: 8
        max-idle: -1
        max-wait: PT10S
#主从哨兵设置
#    sentinel:
#      master:
#      nodes:
#集群配置
#    cluster:
#      nodes:

